import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "InVoices",
  description: "Generated by create Lubos Jurca",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.className} flex flex-col sm:flex-row bg-11`}
      >
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
